/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.4).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.co.reto.zara.controller;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import com.co.reto.zara.model.JsonApiBodyRequest;
import com.co.reto.zara.model.JsonApiBodyResponseErrors;
import com.co.reto.zara.model.JsonApiBodyResponseSuccess;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponses;
import javax.validation.Valid;
import io.swagger.annotations.*;


@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2023-02-30T10:40:36.583176100-05:00[America/Bogota]")
@Api(value = "getPrice", description = "the getPrice API")
public interface GetPriceApi {

    @ApiOperation(value = "consult the information of the prices of a product given certain business conditions", nickname = "getDeatil", notes = "consult the information of the prices of a product given certain business conditions", response = JsonApiBodyResponseSuccess.class, responseContainer = "JsonObjetc", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "search results matching criteria", response = JsonApiBodyResponseSuccess.class, responseContainer = "JsonObjetc"),
        @ApiResponse(code = 424, message = "bad input parameter", response = JsonApiBodyResponseErrors.class, responseContainer = "JsonObjetc") })
    @RequestMapping(value = "/getPrice",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<?> getDeatil(@Valid @RequestBody JsonApiBodyRequest body) throws Exception;

}
